name: Deploy to WordPress.org

on:
  push:
    tags:
    - "*"

jobs:
  tag:
    name: New tag
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2.4.0

    - name: WordPress.org Plugin Deploy
      uses: 10up/action-wordpress-plugin-deploy@2.0.0
      env:
        SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
        SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
        SLUG: wpt-custom-mo-file
